<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
	<PropertyGroup>
		<VersionPrefix>5.3.0</VersionPrefix>
		<VersionSuffix>pre</VersionSuffix>
	</PropertyGroup>
	<PropertyGroup Label="Configuration">
		<RootNamespace>NetTally</RootNamespace>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<RollForward>LatestMajor</RollForward>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>
	<PropertyGroup>
		<Product>NetTally</Product>
		<Company>Wayward Gamers</Company>
		<Copyright>2015-2025</Copyright>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.7" />
		<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="NetTally.dll.config">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>