<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
	<PropertyGroup>
		<VersionPrefix>5.0.6</VersionPrefix>
	</PropertyGroup>
	<PropertyGroup Label="Configuration">
		<RootNamespace>NetTally</RootNamespace>
		<TargetFramework>net8.0</TargetFramework>
		<RollForward>LatestMajor</RollForward>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<Product>NetTally</Product>
		<Company>Wayward Gamers</Company>
		<Copyright>2015-2024</Copyright>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
		<PackageReference Include="Nito.AsyncEx.Coordination" Version="5.1.2" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="NetTally.dll.config">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>